apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: vote
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: psql-storage
          mountPath: /var/lib/postgresql/data
        envFrom:
        - secretRef:
            name: db-secrets

      volumes:
      - name: psql-storage
        persistentVolumeClaim:
          claimName: db-volume-claim


---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db_psql_0001"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
  namespace: vote
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi